"""add task_group_attachment table

Revision ID: 01a5f642e62f
Revises: f1aafac0b11e
Create Date: 2026-08-16 18:28:00.794895

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01a5f642e62f"
down_revision: Union[str, Sequence[str], None] = "f1aafac0b11e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_group_attachment",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_group_id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False
        ),
        sa.Column(
            "object_storage_path",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "external_url", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_group_id"],
            ["task_group.id"],
            name="fk_task_group_attachment_task_group",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_group_attachment_task_group",
        "task_group_attachment",
        ["task_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_task_group_attachment_task_group", table_name="task_group_attachment"
    )
    op.drop_table("task_group_attachment")
    # ### end Alembic commands ###
