"""add export_job, export_job_task_group, storage_usage_snapshot tables

Revision ID: 1da01633ce0f
Revises: fd48262b43f0
Create Date: 2026-08-17 15:53:56.072794

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1da01633ce0f"
down_revision: Union[str, Sequence[str], None] = "fd48262b43f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_job",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "requested_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storage_usage_snapshot",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "checked_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column("db_used_bytes", sa.Integer(), nullable=False),
        sa.Column("object_storage_used_bytes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "export_job_task_group",
        sa.Column("export_job_id", sa.Integer(), nullable=False),
        sa.Column("task_group_id", sa.Integer(), nullable=False),
        sa.Column("db_bytes_freed", sa.Integer(), nullable=True),
        sa.Column("object_storage_bytes_freed", sa.Integer(), nullable=True),
        sa.Column(
            "is_source_deleted",
            sa.String(length=1),
            server_default=sa.text("'N'"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["export_job_id"],
            ["export_job.id"],
            name="fk_export_job_task_group_export_job",
        ),
        sa.ForeignKeyConstraint(
            ["task_group_id"],
            ["task_group.id"],
            name="fk_export_job_task_group_task_group",
        ),
        sa.PrimaryKeyConstraint("export_job_id", "task_group_id"),
    )
    op.create_index(
        "ix_export_job_task_group_task_group",
        "export_job_task_group",
        ["task_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_export_job_task_group_task_group", table_name="export_job_task_group"
    )
    op.drop_table("export_job_task_group")
    op.drop_table("storage_usage_snapshot")
    op.drop_table("export_job")
    # ### end Alembic commands ###
