"""add task, task_activity_log, task_comment tables

Revision ID: 2061a01e4956
Revises: 01a5f642e62f
Create Date: 2026-08-16 19:10:09.371587

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2061a01e4956"
down_revision: Union[str, Sequence[str], None] = "01a5f642e62f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column(
            "status",
            sa.String(length=10),
            server_default=sa.text("'보류'"),
            nullable=False,
        ),
        sa.Column("estimated_days", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_group_id"], ["task_group.id"], name="fk_task_task_group"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_task_dates", "task", ["start_date", "due_date"], unique=False)
    op.create_index("ix_task_status", "task", ["status"], unique=False)
    op.create_index("ix_task_task_group", "task", ["task_group_id"], unique=False)
    op.create_table(
        "task_activity_log",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "event_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "old_value", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.Column(
            "new_value", sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True
        ),
        sa.Column(
            "reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_task_activity_log_task"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_activity_log_task_time",
        "task_activity_log",
        ["task_id", "event_at"],
        unique=False,
    )
    op.create_table(
        "task_comment",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.CLOB(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], name="fk_task_comment_task"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_comment_task_time",
        "task_comment",
        ["task_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_comment_task_time", table_name="task_comment")
    op.drop_table("task_comment")
    op.drop_index("ix_task_activity_log_task_time", table_name="task_activity_log")
    op.drop_table("task_activity_log")
    op.drop_index("ix_task_task_group", table_name="task")
    op.drop_index("ix_task_status", table_name="task")
    op.drop_index("ix_task_dates", table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
