"""add task_assignee, task_dependency tables

Revision ID: 6703acb6ae15
Revises: 2061a01e4956
Create Date: 2026-08-16 21:21:31.520635

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6703acb6ae15"
down_revision: Union[str, Sequence[str], None] = "2061a01e4956"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_assignee",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], name="fk_task_assignee_person"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], name="fk_task_assignee_task"),
        sa.PrimaryKeyConstraint("task_id", "person_id"),
    )
    op.create_index(
        "ix_task_assignee_person", "task_assignee", ["person_id"], unique=False
    )
    op.create_table(
        "task_dependency",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_task_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["task.id"],
            name="fk_task_dependency_depends_on_task",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name="fk_task_dependency_task"
        ),
        sa.PrimaryKeyConstraint("task_id", "depends_on_task_id"),
    )
    op.create_index(
        "ix_task_dependency_depends_on_task",
        "task_dependency",
        ["depends_on_task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_dependency_depends_on_task", table_name="task_dependency")
    op.drop_table("task_dependency")
    op.drop_index("ix_task_assignee_person", table_name="task_assignee")
    op.drop_table("task_assignee")
    # ### end Alembic commands ###
