"""add task_group table

Revision ID: f1aafac0b11e
Revises: 6a7b200ed555
Create Date: 2026-08-16 17:41:07.466171

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1aafac0b11e"
down_revision: Union[str, Sequence[str], None] = "6a7b200ed555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_group",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sa.CLOB(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=10),
            server_default=sa.text("'진행중'"),
            nullable=False,
        ),
        sa.Column(
            "is_archived",
            sa.String(length=1),
            server_default=sa.text("'N'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_group_category_status",
        "task_group",
        ["category", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_group_category_status", table_name="task_group")
    op.drop_table("task_group")
    # ### end Alembic commands ###
