"""add meeting, meeting_attendee, meeting_task tables

Revision ID: fd48262b43f0
Revises: 6703acb6ae15
Create Date: 2026-08-16 22:06:59.240554

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd48262b43f0"
down_revision: Union[str, Sequence[str], None] = "6703acb6ae15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting",
        sa.Column("id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("task_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=10),
            server_default=sa.text("'예정'"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("agenda", sa.CLOB(), nullable=True),
        sa.Column("content", sa.CLOB(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("SYSTIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_group_id"], ["task_group.id"], name="fk_meeting_task_group"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_meeting_task_group", "meeting", ["task_group_id"], unique=False)
    op.create_table(
        "meeting_attendee",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["meeting.id"], name="fk_meeting_attendee_meeting"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["person.id"], name="fk_meeting_attendee_person"
        ),
        sa.PrimaryKeyConstraint("meeting_id", "person_id"),
    )
    op.create_index(
        "ix_meeting_attendee_person", "meeting_attendee", ["person_id"], unique=False
    )
    op.create_table(
        "meeting_task",
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["meeting.id"], name="fk_meeting_task_meeting"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], name="fk_meeting_task_task"),
        sa.PrimaryKeyConstraint("meeting_id", "task_id"),
    )
    op.create_index("ix_meeting_task_task", "meeting_task", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meeting_task_task", table_name="meeting_task")
    op.drop_table("meeting_task")
    op.drop_index("ix_meeting_attendee_person", table_name="meeting_attendee")
    op.drop_table("meeting_attendee")
    op.drop_index("ix_meeting_task_group", table_name="meeting")
    op.drop_table("meeting")
    # ### end Alembic commands ###
