/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_api_v1_persons_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_v1_persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_v1_persons__person_id__get"];
        put?: never;
        post?: never;
        /** Delete Person */
        delete: operations["delete_person_api_v1_persons__person_id__delete"];
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_api_v1_persons__person_id__patch"];
        trace?: never;
    };
    "/api/v1/task-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Groups */
        get: operations["list_task_groups_api_v1_task_groups_get"];
        put?: never;
        /** Create Task Group */
        post: operations["create_task_group_api_v1_task_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-groups/{task_group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Group */
        get: operations["get_task_group_api_v1_task_groups__task_group_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task Group
         * @description API 설계 5.2절 순서: 하위 Task마다(각자 캐스케이드 포함) →
         *     참고자료 → 하위 미팅마다(각자 캐스케이드 포함) → TaskGroup 행.
         */
        delete: operations["delete_task_group_api_v1_task_groups__task_group_id__delete"];
        options?: never;
        head?: never;
        /** Update Task Group */
        patch: operations["update_task_group_api_v1_task_groups__task_group_id__patch"];
        trace?: never;
    };
    "/api/v1/task-groups/{task_group_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attachments */
        get: operations["list_attachments_api_v1_task_groups__task_group_id__attachments_get"];
        put?: never;
        /** Create Attachment */
        post: operations["create_attachment_api_v1_task_groups__task_group_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attachment */
        delete: operations["delete_attachment_api_v1_attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-groups/{task_group_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_task_groups__task_group_id__tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_task_groups__task_group_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task Status */
        patch: operations["update_task_status_api_v1_tasks__task_id__status_patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task Schedule */
        patch: operations["update_task_schedule_api_v1_tasks__task_id__schedule_patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/activity-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activity Log */
        get: operations["list_activity_log_api_v1_tasks__task_id__activity_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["list_comments_api_v1_tasks__task_id__comments_get"];
        put?: never;
        /** Create Comment */
        post: operations["create_comment_api_v1_tasks__task_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Comment */
        delete: operations["delete_comment_api_v1_comments__comment_id__delete"];
        options?: never;
        head?: never;
        /** Update Comment */
        patch: operations["update_comment_api_v1_comments__comment_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Meetings */
        get: operations["list_task_meetings_api_v1_tasks__task_id__meetings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignees */
        get: operations["list_assignees_api_v1_tasks__task_id__assignees_get"];
        put?: never;
        /** Add Assignee */
        post: operations["add_assignee_api_v1_tasks__task_id__assignees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/assignees/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Assignee */
        delete: operations["remove_assignee_api_v1_tasks__task_id__assignees__person_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dependencies */
        get: operations["list_dependencies_api_v1_tasks__task_id__dependencies_get"];
        put?: never;
        /** Add Dependency */
        post: operations["add_dependency_api_v1_tasks__task_id__dependencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/dependencies/{depends_on_task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Dependency */
        delete: operations["remove_dependency_api_v1_tasks__task_id__dependencies__depends_on_task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-groups/{task_group_id}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_v1_task_groups__task_group_id__meetings_get"];
        put?: never;
        /** Create Meeting */
        post: operations["create_meeting_api_v1_task_groups__task_group_id__meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_api_v1_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Delete Meeting */
        delete: operations["delete_meeting_api_v1_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /** Update Meeting */
        patch: operations["update_meeting_api_v1_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/attendees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Meeting Attendee */
        post: operations["add_meeting_attendee_api_v1_meetings__meeting_id__attendees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/attendees/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Meeting Attendee */
        delete: operations["remove_meeting_attendee_api_v1_meetings__meeting_id__attendees__person_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Meeting Task */
        post: operations["add_meeting_task_api_v1_meetings__meeting_id__tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Meeting Task */
        delete: operations["remove_meeting_task_api_v1_meetings__meeting_id__tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_api_v1_storage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_v1_storage_exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_v1_storage_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/exports/{export_job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_api_v1_storage_exports__export_job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/exports/{export_job_id}/task-groups/{task_group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive Delete
         * @description export가 이미 완료돼 로컬에 저장됐다고 사용자가 확인한 뒤에만
         *     호출되는, 원본 삭제를 확정하는 별도 엔드포인트다(0번 섹션 ④).
         */
        delete: operations["archive_delete_api_v1_storage_exports__export_job_id__task_groups__task_group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttachmentType
         * @description 참고자료가 업로드 파일인지, 외부 URL 링크인지 구분한다.
         * @enum {string}
         */
        AttachmentType: "파일" | "URL";
        /** Body_create_attachment_api_v1_task_groups__task_group_id__attachments_post */
        Body_create_attachment_api_v1_task_groups__task_group_id__attachments_post: {
            type: components["schemas"]["AttachmentType"];
            /** Title */
            title: string;
            /** External Url */
            external_url?: string | null;
            /** File */
            file?: string | null;
        };
        /** ExportCreate */
        ExportCreate: {
            /** Task Group Ids */
            task_group_ids: number[];
        };
        /** ExportJobRead */
        ExportJobRead: {
            /** Id */
            id: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Task Groups */
            task_groups: components["schemas"]["ExportJobTaskGroupRead"][];
        };
        /** ExportJobTaskGroupRead */
        ExportJobTaskGroupRead: {
            /** Task Group Id */
            task_group_id: number;
            /** Db Bytes Freed */
            db_bytes_freed: number | null;
            /** Object Storage Bytes Freed */
            object_storage_bytes_freed: number | null;
            /** Is Source Deleted */
            is_source_deleted: boolean;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingAttendeeAdd */
        MeetingAttendeeAdd: {
            /** Person Id */
            person_id: number;
        };
        /** MeetingCreate */
        MeetingCreate: {
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Agenda */
            agenda?: string | null;
            /**
             * Attendee Person Ids
             * @default []
             */
            attendee_person_ids: number[];
            /**
             * Task Ids
             * @default []
             */
            task_ids: number[];
        };
        /** MeetingRead */
        MeetingRead: {
            /** Id */
            id: number;
            /** Task Group Id */
            task_group_id: number;
            status: components["schemas"]["MeetingStatus"];
            /** Scheduled At */
            scheduled_at: string;
            /** Agenda */
            agenda: string | null;
            /** Content */
            content: string | null;
            /**
             * Attendees
             * @default []
             */
            attendees: components["schemas"]["PersonRead"][];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["TaskRead"][];
        };
        /**
         * MeetingStatus
         * @description 미팅 상태. Task/TaskGroup의 TaskStatus와 값이 달라 공유하지 않는다.
         * @enum {string}
         */
        MeetingStatus: "예정" | "완료";
        /** MeetingTaskAdd */
        MeetingTaskAdd: {
            /** Task Id */
            task_id: number;
        };
        /** MeetingUpdate */
        MeetingUpdate: {
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Agenda */
            agenda?: string | null;
            /** Content */
            content?: string | null;
            status?: components["schemas"]["MeetingStatus"] | null;
        };
        /** PersonCreate */
        PersonCreate: {
            category: components["schemas"]["Scope"];
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Affiliation */
            affiliation?: string | null;
        };
        /** PersonRead */
        PersonRead: {
            /** Id */
            id: number;
            category: components["schemas"]["Scope"];
            /** Name */
            name: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Affiliation */
            affiliation: string | null;
        };
        /** PersonUpdate */
        PersonUpdate: {
            category?: components["schemas"]["Scope"] | null;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Affiliation */
            affiliation?: string | null;
        };
        /**
         * Scope
         * @description 개인 소유인지 회사 소속인지 구분하는 레벨1 분류.
         *
         *     Person.category, (앞으로 생길) Level2.category가 공유한다.
         *     두 엔티티가 각자 같은 값을 따로 정의하면 나중에 하나만 바뀌었을 때
         *     불일치가 생길 수 있어서 여기 하나로 모아둔다.
         * @enum {string}
         */
        Scope: "회사" | "개인";
        /** StorageQuota */
        StorageQuota: {
            /** Used Bytes */
            used_bytes: number;
            /** Limit Bytes */
            limit_bytes: number;
            /** Percent */
            percent: number;
        };
        /** StorageUsageRead */
        StorageUsageRead: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            db: components["schemas"]["StorageQuota"];
            object_storage: components["schemas"]["StorageQuota"];
            /** Warnings */
            warnings: string[];
        };
        /** TaskActivityLogRead */
        TaskActivityLogRead: {
            /** Id */
            id: number;
            /** Event Type */
            event_type: string;
            /**
             * Event At
             * Format: date-time
             */
            event_at: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            /** Reason */
            reason: string | null;
        };
        /** TaskAssigneeAdd */
        TaskAssigneeAdd: {
            /** Person Id */
            person_id: number;
        };
        /** TaskCommentCreate */
        TaskCommentCreate: {
            /** Content */
            content: string;
        };
        /** TaskCommentRead */
        TaskCommentRead: {
            /** Id */
            id: number;
            /** Task Id */
            task_id: number;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TaskCommentUpdate */
        TaskCommentUpdate: {
            /** Content */
            content: string;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Name */
            name: string;
            /** Estimated Days */
            estimated_days?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** TaskDependencyAdd */
        TaskDependencyAdd: {
            /** Depends On Task Id */
            depends_on_task_id: number;
        };
        /** TaskGroupAttachmentRead */
        TaskGroupAttachmentRead: {
            /** Id */
            id: number;
            /** Task Group Id */
            task_group_id: number;
            type: components["schemas"]["AttachmentType"];
            /** Title */
            title: string;
            /** Object Storage Path */
            object_storage_path: string | null;
            /** External Url */
            external_url: string | null;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /** Mime Type */
            mime_type: string | null;
        };
        /** TaskGroupCreate */
        TaskGroupCreate: {
            category: components["schemas"]["Scope"];
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** @default 진행중 */
            status: components["schemas"]["TaskStatus"];
        };
        /** TaskGroupProgress */
        TaskGroupProgress: {
            /** Total Tasks */
            total_tasks: number;
            /** Done Tasks */
            done_tasks: number;
            /** Percent */
            percent: number;
        };
        /** TaskGroupRead */
        TaskGroupRead: {
            /** Id */
            id: number;
            category: components["schemas"]["Scope"];
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Is Archived */
            is_archived: boolean;
            /** Created At */
            created_at: string | null;
            progress?: components["schemas"]["TaskGroupProgress"] | null;
        };
        /** TaskGroupUpdate */
        TaskGroupUpdate: {
            category?: components["schemas"]["Scope"] | null;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
        };
        /** TaskRead */
        TaskRead: {
            /** Id */
            id: number;
            /** Task Group Id */
            task_group_id: number;
            /** Name */
            name: string;
            status: components["schemas"]["TaskStatus"];
            /** Estimated Days */
            estimated_days: number | null;
            /** Start Date */
            start_date: string | null;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** TaskScheduleUpdate */
        TaskScheduleUpdate: {
            /** Start Date */
            start_date?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * TaskStatus
         * @description 레벨2·레벨3이 공유하는 진행 상태.
         *
         *     레벨2 기본값은 '진행중', 레벨3 기본값은 '보류'로 서로 다르다 —
         *     값 목록 자체는 같아서 여기 하나로 모아둔다.
         * @enum {string}
         */
        TaskStatus: "보류" | "진행중" | "완료";
        /** TaskStatusUpdate */
        TaskStatusUpdate: {
            status: components["schemas"]["TaskStatus"];
        };
        /** TaskUpdate */
        TaskUpdate: {
            /** Name */
            name?: string | null;
            /** Estimated Days */
            estimated_days?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_persons_api_v1_persons_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Scope"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_person_api_v1_persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_v1_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_person_api_v1_persons__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person_api_v1_persons__person_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_groups_api_v1_task_groups_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Scope"] | null;
                status?: components["schemas"]["TaskStatus"] | null;
                include_archived?: boolean;
                created_after?: string | null;
                created_before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_group_api_v1_task_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_group_api_v1_task_groups__task_group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_group_api_v1_task_groups__task_group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_group_api_v1_task_groups__task_group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attachments_api_v1_task_groups__task_group_id__attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupAttachmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attachment_api_v1_task_groups__task_group_id__attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_attachment_api_v1_task_groups__task_group_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskGroupAttachmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_api_v1_attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_task_groups__task_group_id__tasks_get: {
        parameters: {
            query?: {
                view?: string;
            };
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_task_groups__task_group_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_status_api_v1_tasks__task_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_schedule_api_v1_tasks__task_id__schedule_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_log_api_v1_tasks__task_id__activity_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskActivityLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comments_api_v1_tasks__task_id__comments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_api_v1_tasks__task_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCommentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_comment_api_v1_comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_comment_api_v1_comments__comment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCommentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCommentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_meetings_api_v1_tasks__task_id__meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignees_api_v1_tasks__task_id__assignees_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_assignee_api_v1_tasks__task_id__assignees_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskAssigneeAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_assignee_api_v1_tasks__task_id__assignees__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dependencies_api_v1_tasks__task_id__dependencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_dependency_api_v1_tasks__task_id__dependencies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDependencyAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_dependency_api_v1_tasks__task_id__dependencies__depends_on_task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                depends_on_task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meetings_api_v1_task_groups__task_group_id__meetings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_v1_task_groups__task_group_id__meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_v1_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_v1_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_api_v1_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_meeting_attendee_api_v1_meetings__meeting_id__attendees_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingAttendeeAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_meeting_attendee_api_v1_meetings__meeting_id__attendees__person_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_meeting_task_api_v1_meetings__meeting_id__tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingTaskAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_meeting_task_api_v1_meetings__meeting_id__tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_v1_storage_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUsageRead"];
                };
            };
        };
    };
    list_exports_api_v1_storage_exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobRead"][];
                };
            };
        };
    };
    create_export_api_v1_storage_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_v1_storage_exports__export_job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_delete_api_v1_storage_exports__export_job_id__task_groups__task_group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_job_id: number;
                task_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
